CREATE TABLE USER(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50),
	address VARCHAR(50),
	sex VARCHAR(5),
	email VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL
);